= Zendesk Ticket Viewer
Jack Jordan <contact@jackjordan.io>

== What is this?
This is my ticket viewer for the Zendesk internship coding challenge.

== How do I use it?
Run "Zendesk Ticket Viewer.py" in Python 3 (tested in 3.5). Once you have started the program, it will prompt you to enter your Zendesk subdomain (from your Zendesk domain, {subdomain}.zendesk.com, enter it without the {}). It will then ask for your email address (that you use to log in to Zendesk) and your password.

After you have done this it will download all the tickets on your account. This may take a few seconds. Once it has downloaded the tickets, it will display details for the first 25 tickets.

The tickets are in this format:

Ticket **id**: **first 20 characters of subject**(...) requested by **requester's name** on **date**

From here it will give you a number of input prompts. You can enter a letter (case insensitive) in brackets or a ticket ID (from those displayed) to execute the relevant command.

After you check the full details of a ticket. You must press enter to continue back to the paged list. This is to give you time to read the details without them being pushed off the screen.

== Known issues
The program will crash if you have no internet connection. I don't know how to fix this but the software is useless if you don't have a connection so it is not super important to fix.

This **may** cause a crash if there is no API response but I am not sure.
